server:
  port: 8080  # API Gateway port
  address: 0.0.0.0

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # Route to backend-service
        - id: backend-service
          # Docker container name; uri does not accept underscore _
          uri: http://backend-service.prj-deployment-mgmt.svc.cluster.local:8082
          predicates:
            - Path=/api/metrics/**
          filters:
            - StripPrefix=0  # Keep the full path

        # Route to database-service
        - id: database-service
          # Docker container name; uri does not accept underscore _
          uri: http://database-service.prj-deployment-mgmt.svc.cluster.local:8081
          predicates:
            - Path=/api/deployments/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: DEBUG